services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - "25432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  pgdata: