"""problem

Revision ID: a636b1edbde0
Revises: 8eb889ebaf96
Create Date: 2025-04-23 08:49:54.589875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a636b1edbde0"
down_revision: Union[str, None] = "8eb889ebaf96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("input_example", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output_example", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("concepts", sa.JSON(), nullable=False),
        sa.Column("code_skeleton", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("code_lang", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_lang", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("test_case", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("approach_hints", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_problem_title"), "problem", ["title"], unique=False)
    op.add_column(
        "user", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "user", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_index(op.f("ix_problem_title"), table_name="problem")
    op.drop_table("problem")
    # ### end Alembic commands ###
